name: d2l
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - attr=2.5.2
  - attrs=24.3.0
  - babel=2.17.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - comm=0.2.3
  - contourpy=1.3.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.14.1
  - glib=2.86.3
  - glib-tools=2.86.3
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.2.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipython_genutils=0.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.8.1
  - jupyter_server=1.24.0
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.15
  - keyutils=1.6.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.7
  - libclang13=21.1.7
  - libcups=2.3.3
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libllvm21=21.1.8
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.25
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=18.1
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=257.10
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mpg123=1.32.9
  - munkres=1.1.4
  - nbclassic=0.5.6
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - nspr=4.38
  - nss=3.118
  - numpy=1.23.5
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.0.3
  - pandoc=3.8.3
  - parso=0.8.4
  - pcre2=10.47
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - ply=3.11
  - pooch=1.8.2
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.0.9
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyrsistent=0.20.0
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyzmq=27.0.2
  - qt-main=5.15.15
  - readline=8.3
  - scipy=1.10.1
  - send2trash=1.8.3
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - sniffio=1.3.1
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025c
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
    - alabaster==0.7.16
    - anyio==4.12.0
    - arrow==1.4.0
    - astor==0.8.1
    - async-lru==2.0.5
    - autopep8==2.3.2
    - awscli==1.44.4
    - beautifulsoup4==4.14.3
    - bleach==6.2.0
    - botocore==1.42.14
    - cmake==4.2.0
    - colorama==0.4.6
    - commonmark==0.9.1
    - d2l==1.0.3
    - d2l-notedown==2.1.0
    - d2lbook==1.0.3
    - datasets==4.4.2
    - dill==0.4.0
    - docutils==0.17.1
    - fasteners==0.20
    - fqdn==1.5.1
    - gitdb==4.0.12
    - gitpython==3.1.45
    - imagesize==1.4.1
    - ipython-pygments-lexers==1.1.1
    - ipywidgets==8.1.8
    - isoduration==20.11.0
    - isort==6.1.0
    - jmespath==1.0.1
    - jsonpointer==3.0.0
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter-server==2.17.0
    - jupyter-server-terminals==0.5.3
    - lark==1.3.1
    - latexcodec==3.0.1
    - lit==18.1.8
    - markupsafe==3.0.3
    - matplotlib-inline==0.1.6
    - mistune==3.1.4
    - mpmath==1.3.0
    - mu-notedown==2.0.3
    - multiprocess==0.70.18
    - mxtheme==0.3.17
    - networkx==3.2.1
    - numpydoc==1.6.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - overrides==7.7.0
    - pandoc-attributes==0.1.7
    - pandocfilters==1.5.1
    - pyarrow==21.0.0
    - pyasn1==0.6.1
    - pybtex==0.24.0
    - pybtex-apa-style==1.3
    - pybtex-docutils==1.0.3
    - pycodestyle==2.14.0
    - python-json-logger==4.0.0
    - qtconsole==5.7.0
    - qtpy==2.4.3
    - recommonmark==0.7.1
    - regex==2025.11.3
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rsa==4.7.2
    - s3transfer==0.16.0
    - smmap==5.0.2
    - snowballstemmer==3.0.1
    - soupsieve==2.8.1
    - sphinx==5.3.0
    - sphinx-autodoc-typehints==1.23.0
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-bibtex==2.4.2
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - sphinxcontrib-svg2pdfconverter==2.0.0
    - sympy==1.14.0
    - tabulate==0.9.0
    - torch==2.0.0
    - torchvision==0.15.1
    - tqdm==4.67.1
    - triton==2.0.0
    - uri-template==1.3.0
    - urllib3==1.26.20
    - webcolors==24.11.1
    - websocket-client==1.9.0
    - widgetsnbextension==4.0.15
    - xxhash==3.6.0
    - yapf==0.43.0
prefix: /home/kzy816/.conda/envs/d2l
