name: d2l
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - appnope=0.1.4
  - asttokens=3.0.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - comm=0.2.3
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fonttools=4.59.1
  - freetype=2.14.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.25
  - libpng=1.6.53
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.23.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.0.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.3.8
  - pooch=1.8.2
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyzmq=27.0.2
  - readline=8.3
  - scipy=1.10.1
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025c
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - alabaster==0.7.16
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astor==0.8.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - autopep8==2.3.2
      - awscli==1.44.4
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.2.0
      - botocore==1.42.14
      - colorama==0.4.6
      - commonmark==0.9.1
      - d2l==1.0.3
      - d2l-notedown==2.1.0
      - d2lbook==1.0.3
      - defusedxml==0.7.1
      - docutils==0.17.1
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - imagesize==1.4.1
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - isort==6.1.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - latexcodec==3.0.1
      - markupsafe==3.0.3
      - matplotlib-inline==0.1.6
      - mistune==3.1.4
      - mpmath==1.3.0
      - mu-notedown==2.0.3
      - mxtheme==0.3.17
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.2.1
      - notebook==7.5.1
      - notebook-shim==0.2.4
      - numpydoc==1.6.0
      - overrides==7.7.0
      - pandoc-attributes==0.1.7
      - pandocfilters==1.5.1
      - prometheus-client==0.23.1
      - pyasn1==0.6.1
      - pybtex==0.25.1
      - pybtex-apa-style==1.3
      - pybtex-docutils==1.0.3
      - pycodestyle==2.14.0
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - recommonmark==0.7.1
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - rsa==4.7.2
      - s3transfer==0.16.0
      - send2trash==1.8.3
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.8.1
      - sphinx==5.3.0
      - sphinx-autodoc-typehints==1.23.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.5
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sphinxcontrib-svg2pdfconverter==2.0.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.3.0
      - torch==2.0.0
      - torchvision==0.15.1
      - typing-extensions==4.15.0
      - uri-template==1.3.0
      - urllib3==1.26.20
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - yapf==0.43.0
